from enum import Enum


class Verdict(str, Enum):
    READY_LONG = "READY_LONG"
    WATCH = "WATCH"
    AVOID = "AVOID"
    TRIM_SELL = "TRIM_SELL"
    NEUTRAL = "NEUTRAL"


class Phase(str, Enum):
    ACCUMULATION = "ACCUMULATION"
    EARLY_MARKUP = "EARLY_MARKUP"
    MARKUP = "MARKUP"
    LATE_MARKUP = "LATE_MARKUP"
    DISTRIBUTION = "DISTRIBUTION"
    MARKDOWN = "MARKDOWN"
    BOTTOMING = "BOTTOMING"
    REBOUND = "REBOUND"
    NOISY_NEUTRAL = "NOISY_NEUTRAL"
    COMPRESSION = "COMPRESSION"
    BREAKOUT_ATTEMPT = "BREAKOUT_ATTEMPT"
    FAILED_BREAKOUT = "FAILED_BREAKOUT"
